export const editorConfig = {
  addNewLine: false,
  readonly: false,
  uploader: { insertImageAsBase64URI: true },
  toolbar: true,
  spellcheck: false,
  language: 'en',
  toolbarButtonSize: 'medium',
  toolbarAdaptive: false,
  showCharsCounter: false,
  showWordsCounter: false,
  showXPathInStatusbar: false,
  askBeforePasteHTML: false,
  askBeforePasteFromWord: false,
  width: 'auto',
  height: '65vh',
  imageDefaultWidth: 300,
  placeholder: '',
  buttons: [
    'bold',
    'strikethrough',
    'underline',
    'italic',
    'ul',
    'ol',
    'outdent',
    'indent',
    'fontsize',
    'paragraph',
    'align',
    'undo',
    'redo',
    'hr',
    'image',
    'table',
    'fullsize',
  ],
  buttonsXS: ['bold', 'image', 'paragraph', 'align', 'undo', 'redo'],
};
